# hocus pocus pilatus pas
LEFT = -1
CENTER = 0
RIGHT = 1
UP = 2
DOWN = -2
DEFAULT_SIDE = LEFT
ROTATE_RIGHT = 3
ROTATE_LEFT = -3
TURN_RIGHT = 4
TURN_LEFT = -4
keys = {
    UP: "UP",
    DOWN: "DOWN",
    RIGHT: "RIGHT",
    LEFT: "LEFT",
    CENTER: "CENTER",
    ROTATE_LEFT: "ROTATE_LEFT",
    ROTATE_RIGHT: "ROTATE_RIGHT",
    TURN_LEFT: "TURN_LEFT",
    TURN_RIGHT: "TURN_RIGHT",
}
